before:
  hooks:
    - go mod download
builds:
  - id: cxgo
    main: ./cmd/cxgo
    ldflags:
      - -s -w
      - -X main.version={{ .Tag }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^examples:'
      - '^test:'
      - '^ci:'
